name: Update Space Shooter GIF

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Create assets folder
      - name: Create assets folder
        run: mkdir -p assets

      # 3. Install Space Shooter
      - name: Install Space Shooter
        run: |
          python -m pip install --upgrade pip
          python -m pip install gh-space-shooter

      # 4. Generate contribution Space Shooter
      - name: Generate Space Shooter
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh-space-shooter "${{ github.repository_owner }}" \
            --output assets/space-shooter-color.gif \
            --strategy random

      # 5. Install Pillow
      - name: Install Pillow
        run: |
          python -m pip install pillow

      # 6. Convert GIF to black and white
      - name: Convert GIF to Monochrome
        run: |
          python - <<'PY'
          from PIL import Image, ImageSequence

          source = "assets/space-shooter-color.gif"
          output = "assets/space-shooter.gif"

          image = Image.open(source)

          frames = []
          durations = []

          for frame in ImageSequence.Iterator(image):

              frame = frame.convert("RGBA")

              # Convert all colors to grayscale
              grayscale = frame.convert("L")

              # Preserve transparency
              result = Image.merge(
                  "RGBA",
                  (
                      grayscale,
                      grayscale,
                      grayscale,
                      frame.getchannel("A")
                  )
              )

              frames.append(result)

              durations.append(
                  frame.info.get("duration", 100)
              )

          frames[0].save(
              output,
              save_all=True,
              append_images=frames[1:],
              duration=durations,
              loop=image.info.get("loop", 0),
              optimize=True
          )

          print("Monochrome GIF created successfully.")
          PY

      # 7. Remove temporary colored GIF
      - name: Remove temporary GIF
        run: |
          rm -f assets/space-shooter-color.gif

           # 8. Save the final monochrome GIF
      - name: Commit and Push GIF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/space-shooter.gif

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update monochrome space shooter"
            git push
          fi
